# Site settings
title: "Tech Reborn..."
email: diogo@diogosantos.com
description: "My name is Diogo Santos. I'm a Brazilian software engineer living in Amsterdam with a passion for technology and arts."
baseurl: ""
url: "http://diogosantos.github.io"
twitter_username: diogosantos
github_username:  diogosantos

# Build settings
markdown: kramdown
permalink: pretty
